### ISSUE TITLE
Bimbot.org not working

### ISSUE THREAD

**Issue by benhadad** [opensourceBIM/BIMbots-FreeCAD#2]
The main site bimbot.org is not working.

**Comment by yorikvanhavre** [comment]
Yes apparently the whole BIMbot functionality has been cancelled at BuildingSmart. I think we should mark this addon as obsolete...

**Comment by robroef** [comment]
Not buildingSMART but TNO stopped this (BIMbot) development.

________________________________
Van: Yorik van Havre ***@***.***>
Verzonden: donderdag, juni 6, 2024 2:44 PM
Aan: opensourceBIM/BIMbots-FreeCAD ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [opensourceBIM/BIMbots-FreeCAD] Bimbot.org not working (Issue #2)


Yes apparently the whole BIMbot functionality has been cancelled at BuildingSmart. I think we should mark this addon as obsolete...

**Comment by yorikvanhavre** [comment]
Indeed, I confounded both... Thanks @robroef !

**Comment by hlg** [comment]
Note that the BIMserver project itself is still alive and we also plan to continue working on third party authorisation with OAuth - one of the underlying building blocks of BIMBots. Other BIMBots ideas will not necessarily be picked up or will be dereleased.

**Comment by yorikvanhavre** [comment]
I'd be happy to work on a better version of the [BIMServer integration tool](https://wiki.freecad.org/WebTools_BimServer) we have in FreeCAD... Specially with the new NativeIFC structure we have, this could get a new wind...
